### ISSUE TITLE
Access to dataset

### ISSUE THREAD

**Issue by agaldran** [yueliukth/CSAW-M#16]
Hello,

I am Adrian Galdran, I just requested access to this fantastic dataset via figshare. Sorry for contacting you through an issue, since I guess this is not an issue, but my request is pending approval and at my team we are in a great rush due to deadlines etc. 

I will appreciate a lot if you could review my request and approve it :)

Cheers,

Adrian

**Comment by MoeinSorkhei** [comment]
Hello, thanks for your request. Done.
